PgsTwitter/PgsTwitter/Models/Home/AddObservedModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PgsTwitter.Models.Users
{
    public class AddObservedModel
    {
        public string ObservingUser { get; set; }
        public string ObservedUser { get; set; }
    }
}

PgsTwitter/PgsTwitter/Models/Home/HomeModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PgsTwitter.Models.Home
{
    public class HomeModel
    {
        public string UserName { get; set; }
        public List<string> OtherUsersNames { get; set; }
        public List<string> LikeUserNames { get; set; }
        public List<string> ObservedByUsers { get; set; } 

    }
}

PgsTwitter/PgsTwitter/Models/Home/Message.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PgsTwitter.Models.Home
{
    public class Message
    {
        public string Username { get; set; }
    }
}

PgsTwitter/PgsTwitter/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PgsTwitter.Models.Home;
using PgsTwitter.Models.Users;
using PgsTwitter.Services;

namespace PgsTwitter.Controllers
{
    public class HomeController : BaseController
    {


        //
        // GET: /Home/

        public ActionResult Index()
        {
            var userServices = new UserServices(Context);
            var otherUsers = userServices.List();
            var usersNames = otherUsers.Select(u => u.Username).ToList();
            var loggedUserName = LoginServices.UserName;

            var likedUsers = userServices.GetObserved(loggedUserName);
            var likedByUsers = userServices.GetObserving(loggedUserName);

            var model = new HomeModel()
                {
                    UserName = loggedUserName,
                    OtherUsersNames = usersNames,
                    LikeUserNames = likedUsers,
                    ObservedByUsers = likedByUsers
                };

            return View(model);
        }

        public ActionResult List()
        {
            var model = new Message() {Username = "Zenek"};
            return View(new List<Message>(){model});
        }

        public ActionResult AddObserved(AddObservedModel addObservedModel)
        {
            var usersServices = new UserServices(Context);
            usersServices.AddToObserved(addObservedModel);
            return RedirectToAction("Index");
        }

    }
}

PgsTwitter/PgsTwitter/Controllers/MessageController.cs
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using PgsTwitter.Models.Message;
using PgsTwitter.Services;

namespace PgsTwitter.Controllers
{
    public class MessageController : BaseController
    {
        private IMessageService MessageService { get; set; }

        public MessageController()
        {
            MessageService = new MessageService(Context);
        }

        public ActionResult List(string username)
        {
            //if (username.IsNullOrWhiteSpace())
            //{
            //    username = LoginServices.UserName;
            //}

            var msgs = MessageService.GetMessages(username);
            return View(msgs);
        }

        public ActionResult My()
        {
            var msgs = MessageService.GetMessages(LoginServices.UserName);
            return View("List", msgs);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(AddModel addModel)
        {
            MessageService.PostMessage(LoginServices.UserName, addModel.Text);
            return RedirectToAction("My");
        }
    }
}

PgsTwitter/PgsTwitter/Views/Home/Index.cshtml
@model PgsTwitter.Models.Home.HomeModel

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<p>
    Hello, user @Html.DisplayFor(model => model.UserName) . Do you want to @Html.ActionLink("log out", "LogOut", "Login") ?
</p>
<p>
@Html.ActionLink("Messages", "My", "Message")
</p>
<p>
    All users:

    <ul>
        @{
            foreach (var name in Model.OtherUsersNames)
            {
                <li>
                    @using (Html.BeginForm("AddObserved", "Home"))
                    {
                        @Html.Hidden("ObservingUser", Model.UserName)
                        @Html.Hidden("ObservedUser", name)
                        @name <input type="submit" value="Like!" />
                    }

                </li>
            }
        }

    </ul>
</p>

<p>
    Users like by you:

    <ul>
        @{
            foreach (var user in Model.LikeUserNames)
            {
                <li>@Html.ActionLink(user, "List", "Message", new {username = user}, null)</li>
            }
        }

    </ul>
</p>

<p>
    You are liked by the following users:

    <ul>
        @{
            foreach (var name in Model.ObservedByUsers)
            {
                <li>@name</li>
            }
        }

    </ul>
</p>

PgsTwitter/PgsTwitter/Views/Home/List.cshtml
@model IEnumerable<PgsTwitter.Models.Home.Message>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Username)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>